let

    // configurations start

    Today=Date.From(DateTime.LocalNow()), // today's date

    FromYear = 2010, // set the start year of the date dimension. dates start from 1st of January of this year

    ToYear=2030, // set the end year of the date dimension. dates end at 31st of December of this year

    StartofFiscalYear=10, // set the month number that is start of the financial year. example; if fiscal year start is July, value is 7

    firstDayofWeek=Day.Sunday, // set the week's start day, values: Day.Monday, Day.Sunday....

    // configuration end

    FromDate=#date(FromYear,1,1),

    ToDate=#date(ToYear,12,31),

    Source=List.Dates(

        FromDate,

        Duration.Days(ToDate-FromDate)+1,

        #duration(1,0,0,0)

    ),

    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),

    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),

    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),

    #"Inserted Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),

    #"Inserted Start of Year" = Table.AddColumn(#"Inserted Year", "Start of Year", each Date.StartOfYear([Date]), type date),

    #"Inserted End of Year" = Table.AddColumn(#"Inserted Start of Year", "End of Year", each Date.EndOfYear([Date]), type date),

    #"Inserted Month" = Table.AddColumn(#"Inserted End of Year", "Month", each Date.Month([Date]), Int64.Type),

    #"Inserted Start of Month" = Table.AddColumn(#"Inserted Month", "Start of Month", each Date.StartOfMonth([Date]), type date),

    #"Inserted End of Month" = Table.AddColumn(#"Inserted Start of Month", "End of Month", each Date.EndOfMonth([Date]), type date),

    #"Inserted Days in Month" = Table.AddColumn(#"Inserted End of Month", "Days in Month", each Date.DaysInMonth([Date]), Int64.Type),

    #"Inserted Day" = Table.AddColumn(#"Inserted Days in Month", "Day", each Date.Day([Date]), Int64.Type),

    #"Inserted Day Name" = Table.AddColumn(#"Inserted Day", "Day Name", each Date.DayOfWeekName([Date]), type text),

    #"Inserted Day of Week" = Table.AddColumn(#"Inserted Day Name", "Day of Week", each Date.DayOfWeek([Date],firstDayofWeek), Int64.Type),

    #"Inserted Day of Year" = Table.AddColumn(#"Inserted Day of Week", "Day of Year", each Date.DayOfYear([Date]), Int64.Type),

    #"Inserted Month Name" = Table.AddColumn(#"Inserted Day of Year", "Month Name", each Date.MonthName([Date]), type text),

    #"Inserted Quarter" = Table.AddColumn(#"Inserted Month Name", "Quarter", each Date.QuarterOfYear([Date]), Int64.Type),

    #"Inserted Start of Quarter" = Table.AddColumn(#"Inserted Quarter", "Start of Quarter", each Date.StartOfQuarter([Date]), type date),

    #"Inserted End of Quarter" = Table.AddColumn(#"Inserted Start of Quarter", "End of Quarter", each Date.EndOfQuarter([Date]), type date),

    #"Inserted Week of Year" = Table.AddColumn(#"Inserted End of Quarter", "Week of Year", each Date.WeekOfYear([Date],firstDayofWeek), Int64.Type),

    #"Inserted Week of Month" = Table.AddColumn(#"Inserted Week of Year", "Week of Month", each Date.WeekOfMonth([Date],firstDayofWeek), Int64.Type),

    #"Inserted Start of Week" = Table.AddColumn(#"Inserted Week of Month", "Start of Week", each Date.StartOfWeek([Date],firstDayofWeek), type date),

    #"Inserted End of Week" = Table.AddColumn(#"Inserted Start of Week", "End of Week", each Date.EndOfWeek([Date],firstDayofWeek), type date),

    FiscalMonthBaseIndex=13-StartofFiscalYear,

    adjustedFiscalMonthBaseIndex=if(FiscalMonthBaseIndex>=12 or FiscalMonthBaseIndex<0) then 0 else FiscalMonthBaseIndex,

    #"Added Custom" = Table.AddColumn(#"Inserted End of Week", "FiscalBaseDate", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),

    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"FiscalBaseDate", type date}}),

    #"Inserted Year1" = Table.AddColumn(#"Changed Type1", "Year.1", each Date.Year([FiscalBaseDate]), Int64.Type),

    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Year1",{{"Year.1", "Fiscal Year"}}),

    #"Inserted Quarter1" = Table.AddColumn(#"Renamed Columns1", "Quarter.1", each Date.QuarterOfYear([FiscalBaseDate]), Int64.Type),

    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Quarter1",{{"Quarter.1", "Fiscal Quarter"}}),

    #"Inserted Month1" = Table.AddColumn(#"Renamed Columns2", "Month.1", each Date.Month([FiscalBaseDate]), Int64.Type),

    #"Renamed Columns3" = Table.RenameColumns(#"Inserted Month1",{{"Month.1", "Fiscal Month"}}),

    #"Removed Columns" = Table.RemoveColumns(#"Renamed Columns3",{"FiscalBaseDate"}),

    #"Inserted Age" = Table.AddColumn(#"Removed Columns", "Age", each [Date]-Today, type duration),

    #"Extracted Days" = Table.TransformColumns(#"Inserted Age",{{"Age", Duration.Days, Int64.Type}}),

    #"Renamed Columns4" = Table.RenameColumns(#"Extracted Days",{{"Age", "Day Offset"}}),

    #"Added Custom1" = Table.AddColumn(#"Renamed Columns4", "Month Offset", each (([Year]-Date.Year(Today))*12)

+([Month]-Date.Month(Today))),

    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Month Offset", Int64.Type}}),

    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Year Offset", each [Year]-Date.Year(Today)),

    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom2",{{"Year Offset", Int64.Type}}),

    #"Added Custom3" = Table.AddColumn(#"Changed Type3", "Quarter Offset", each (([Year]-Date.Year(Today))*4)

+([Quarter]-Date.QuarterOfYear(Today))),

    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom3",{{"Quarter Offset", Int64.Type}}),

    #"Added Custom4" = Table.AddColumn(#"Changed Type4", "Year-Month", each Date.ToText([Date],"MMM yyyy")),

    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Year-Month Code", each Date.ToText([Date],"yyyyMM")),

    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Year-Month", type text}, {"Year-Month Code", Int64.Type}}),

    #"Added Custom6" = Table.AddColumn(#"Changed Type5", "FYDate", each Date.AddMonths([Date],adjustedFiscalMonthBaseIndex)),

    #"Inserted Week of Year1" = Table.AddColumn(#"Added Custom6", "FY Week", each "Week " & Number.ToText( Date.WeekOfYear([FYDate]))),

    #"Inserted Week of Year2" = Table.AddColumn(#"Inserted Week of Year1", "Week of Year.1", each Date.WeekOfYear([FYDate]), Int64.Type),

    #"Added Custom7" = Table.AddColumn(#"Inserted Week of Year2", "CurrentDay", each if [Date] <= DateTime.Date(DateTime.LocalNow()) then "Yes" else "No"),

    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "RegWK", each "Week " & Number.ToText([Week of Year])),

    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "MonthYearFY", each Date.MonthName([Date]) & " " & Number.ToText(Date.Year([Date]))),
    #"Added Custom10" = Table.AddColumn(#"Added Custom9", "FYMonthSO", each if [Month] > 9 then [Month] - 9 else [Month] + 3),
    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom10",{{"FYMonthSO", Int64.Type}}),
    #"Added Custom11" = Table.AddColumn(#"Changed Type6", "FYQuatName", each "QTR " & Number.ToText([Fiscal Quarter])),
    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Is Today", each if [Date] = DateTime.Date(DateTime.LocalNow()) then "Today" else [Date]),
    #"Added Conditional Column" = Table.AddColumn(#"Added Custom12", "Is Week", each if [Start of Week] >= DateTime.Date(DateTime.LocalNow()) then [RegWK] else if [End of Week] <= DateTime.Date(DateTime.LocalNow()) then [RegWK] else "This Week"),
    #"Added Custom13" = Table.AddColumn(#"Added Conditional Column", "Is Month", each if [Start of Month] >= DateTime.Date(DateTime.LocalNow()) then [#"Year-Month"] else if [End of Month] <= DateTime.Date(DateTime.LocalNow()) then [#"Year-Month"] else "This Month"),
    #"Added Custom14" = Table.AddColumn(#"Added Custom13", "Is Qtr", each if [Start of Quarter] >= DateTime.Date(DateTime.LocalNow()) then "Qtr-" & Number.ToText([Quarter]) else if [End of Quarter] <= DateTime.Date(DateTime.LocalNow()) then "Qtr-" & Number.ToText([Quarter]) else "This Qtr")
in
    #"Added Custom14"